/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Editar;

import DAO.Conexao;
import DAO.FornecedorDAO;
import DAO.GrupoDAO;
import DAO.HistoricoDAO;
import DAO.ProdutoDAO;
import Model.Fornecedor;
import Model.Grupo;
import Model.Historico;
import Model.Produto;
import Model.Usuario;
import View_Consultar.IEstoque;
import java.awt.Color;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class DEdiProduto extends javax.swing.JDialog {

    public IEstoque telaEstoque;
    String codigoProd = "";//recebe o valor do codigo requisitado para nao ser alterado
    
    /**
     * Creates new form DAddProduto
     */
    private DEdiProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DEdiProduto(java.awt.Frame parent, IEstoque telaEstoque, boolean modal) {
        super(parent, modal);
        initComponents();
        this.telaEstoque = telaEstoque;
        preencheFornecedor();
        preencheGrupos();
        limpar();
    }
    
    public void preencheFornecedor(){
        Connection conexao = Conexao.conectar();
        FornecedorDAO fornecedorDAO = new FornecedorDAO(conexao);
        List<Fornecedor> listaFornecedores = new ArrayList<>();
        listaFornecedores = fornecedorDAO.listarFornecedor();
        for (Fornecedor f : listaFornecedores) {
            fornecedorT.addItem(f.getNome());
        }
        Conexao.desconectar(conexao);
    }
    
    public void preencheGrupos(){
        Connection conexao = Conexao.conectar();
        GrupoDAO grupoDAO = new GrupoDAO(conexao);
        List<Grupo> listaGrupo = new ArrayList<>();
        listaGrupo = grupoDAO.listarGrupo();
        for (Grupo g : listaGrupo) {
            grupoT.addItem(g.getNome());
        }
        Conexao.desconectar(conexao);
    }
    
    public void preencheCampos(String codigo){
        limpar();
        codigoProd = codigo;
        Connection conexao = Conexao.conectar();
        ProdutoDAO produtoDAO = new ProdutoDAO(conexao);
        Produto produto = produtoDAO.selecionarProduto(codigo);
        codigoT.setText(produto.getCodigo());
        nomeT.setEnabled(true);
        nomeT.setText(produto.getNome());
        marcaT.setEnabled(true);
        marcaT.setText(produto.getMarca());
        precoT.setEnabled(true);
        precoT.setText(String.valueOf(produto.getPreco()).replace(".", ","));
        custoT.setEnabled(true);
        custoT.setText(String.valueOf(produto.getCusto()).replace(".", ","));
        quantidadeT.setEnabled(true);
        quantidadeT.setValue(produto.getQuantidade());
        grupoT.setEnabled(true);
        grupoT.setSelectedItem(new GrupoDAO(conexao).selecionarGrupo(produto.getIdGrupo()).getNome());
        entregaT.setEnabled(true);
        entregaT.setDate(produto.getDataEntrega());
        valNula.setEnabled(true);
        if(produto.getDataValidade() == null){
            valNula.setSelected(true);
        }else{
            validadeT.setEnabled(true);
            validadeT.setDate(produto.getDataValidade());
        }
        fornecedorT.setEnabled(true);
        fornecedorT.setSelectedItem(new FornecedorDAO(conexao).selecionarFornecedor(produto.getIdFornecedor()).getNome());
        descricaoT.setEnabled(true);
        descricaoT.setText(produto.getDescricao());
        Conexao.desconectar(conexao);
    }
    
    public void limpar(){
        codigoProd = "";
        codigoT.setText("");
        nomeT.setText("");
        marcaT.setText("");
        precoT.setText("");
        descricaoT.setText("");
        custoT.setText("");
        quantidadeT.setValue(0);
        entregaT.setDate(null);
        validadeT.setDate(null);
        valNula.setSelected(false);
        grupoT.setSelectedIndex(0);
        fornecedorT.setSelectedIndex(0);
        nomeT.setEnabled(false);
        marcaT.setEnabled(false);
        precoT.setEnabled(false);
        descricaoT.setEnabled(false);
        custoT.setEnabled(false);
        quantidadeT.setEnabled(false);
        entregaT.setEnabled(false);
        validadeT.setEnabled(false);
        valNula.setEnabled(false);
        grupoT.setEnabled(false);
        fornecedorT.setEnabled(false);
        codigoT.requestFocus();
        codigoT.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        nomeT = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        quantidadeT = new javax.swing.JSpinner();
        jLabel78 = new javax.swing.JLabel();
        custoT = new javax.swing.JFormattedTextField();
        precoT = new javax.swing.JFormattedTextField();
        jLabel79 = new javax.swing.JLabel();
        marcaT = new javax.swing.JTextField();
        entregaT = new com.toedter.calendar.JDateChooser();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        validadeT = new com.toedter.calendar.JDateChooser();
        jLabel82 = new javax.swing.JLabel();
        fornecedorT = new javax.swing.JComboBox<>();
        jLabel83 = new javax.swing.JLabel();
        grupoT = new javax.swing.JComboBox<>();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        descricaoT = new javax.swing.JTextArea();
        limpar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        fechar = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        valNula = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        codigoT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Produto");
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel73.setText("Editar Produto");

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setText("Código");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setText("Nome");

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel76.setText("Preço Unit.");

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel77.setText("Custo Unit.");

        quantidadeT.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel78.setText("Quantidade");

        custoT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        precoT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel79.setText("Marca");

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel80.setText("Data de Entrega");

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel81.setText("Validade");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel82.setText("Fornecedor");

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel83.setText("Grupo");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel84.setText("Descrição");

        descricaoT.setColumns(20);
        descricaoT.setRows(5);
        descricaoT.setText("Sem descrição.");
        jScrollPane7.setViewportView(descricaoT);

        limpar.setBackground(new java.awt.Color(255, 255, 255));
        limpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        limpar.setText(" Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        confirmar.setBackground(new java.awt.Color(255, 255, 255));
        confirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checked.png"))); // NOI18N
        confirmar.setText(" Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        fechar.setBackground(new java.awt.Color(255, 255, 255));
        fechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006-remove-symbol.png"))); // NOI18N
        fechar.setText(" Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        valNula.setForeground(new java.awt.Color(255, 0, 0));
        valNula.setText("Nula");
        valNula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valNulaActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(234, 234, 234));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        codigoT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoTFocusLost(evt);
            }
        });
        codigoT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(codigoT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoT)
                    .addComponent(buscar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel74)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeT, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel75))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel79)
                            .addComponent(marcaT, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel80)
                                    .addComponent(entregaT, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel81)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(valNula))
                                    .addComponent(validadeT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel76)
                                    .addComponent(precoT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel77)
                                    .addComponent(custoT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel78)
                                    .addComponent(quantidadeT))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fornecedorT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel83)
                                    .addComponent(jLabel82))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {entregaT, validadeT});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel75))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nomeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grupoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel82)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fornecedorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entregaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(valNula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validadeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jLabel84)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {confirmar, fechar, limpar});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {grupoT, quantidadeT});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fornecedorT, validadeT});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        limpar();
    }//GEN-LAST:event_limparActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if(codigoProd.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Produto não selecionado!","ERRO",JOptionPane.ERROR_MESSAGE);
        }else if(codigoT.getText().trim().equals("")
            || nomeT.getText().trim().equals("")
            || marcaT.getText().trim().equals("")
            || precoT.getText().trim().equals("")
            || custoT.getText().trim().equals("")
            || entregaT.getDate() == null
            || ((!valNula.isSelected()) && validadeT.getDate() == null)
            || descricaoT.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Todos os campos precisam ser preenchidos!","ERRO",JOptionPane.ERROR_MESSAGE);
        }else if(Double.parseDouble(custoT.getText().replace(",",".")) >= Double.parseDouble(precoT.getText().replace(",","."))){
            JOptionPane.showMessageDialog(rootPane, "O preço do produto precisa ser maior que o custo!","ERRO",JOptionPane.ERROR_MESSAGE);
        }else if((!valNula.isSelected()) && validadeT.getDate().before(entregaT.getDate())){
            JOptionPane.showMessageDialog(rootPane, "\"Validade\" inválida!\nA data de validade precisa ser depois da data de entrega.","ERRO",JOptionPane.ERROR_MESSAGE);
        }else{
            Connection conexao = Conexao.conectar();
            ProdutoDAO produtoDAO = new ProdutoDAO(conexao);
            Produto produto = new Produto(
                    0,
                    codigoProd,
                    nomeT.getText().trim(),
                    Double.parseDouble(precoT.getText().trim().replace(",", ".")),
                    Double.parseDouble(custoT.getText().trim().replace(",", ".")),
                    entregaT.getDate(),
                    validadeT.getDate(),
                    (int) quantidadeT.getValue(),
                    marcaT.getText().trim(),
                    descricaoT.getText().trim(),
                    new GrupoDAO(conexao).retornaIdGrupo((String) grupoT.getSelectedItem()),
                    new FornecedorDAO(conexao).retornaIdFornecedor((String) fornecedorT.getSelectedItem())
            );
            if (produtoDAO.altProduto(produto)) {
                Historico historico = new Historico(
                    0, 
                    new SimpleDateFormat("yyyy-MM-dd").format(new Date()), 
                    0, 
                    "O produto de código \""+produto.getCodigo()+"\" foi EDITADO.", 
                    Usuario.getIdUser()
                );
                HistoricoDAO historicoDAO = new HistoricoDAO(conexao);
                historicoDAO.addHistorico(historico);
                limpar();
                telaEstoque.preencheTabela();
                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível alterar o produto.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            Conexao.desconectar(conexao);
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharActionPerformed

    private void valNulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valNulaActionPerformed
        if(valNula.isSelected()){
            validadeT.setDate(null);
            validadeT.setEnabled(false);
        }else{
            validadeT.setEnabled(true);
        }
    }//GEN-LAST:event_valNulaActionPerformed

    private void codigoTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTFocusGained
        getRootPane().setDefaultButton(buscar);
    }//GEN-LAST:event_codigoTFocusGained

    private void codigoTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTFocusLost
        getRootPane().setDefaultButton(confirmar);
    }//GEN-LAST:event_codigoTFocusLost

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(codigoT.getText().trim().equals("")){
            limpar();
            JOptionPane.showMessageDialog(rootPane, "Campo \"Código\" vazio!","ERRO",JOptionPane.ERROR_MESSAGE);
        }else{
            Connection conexao = Conexao.conectar();
            ProdutoDAO produtoDAO = new ProdutoDAO(conexao);
            if(produtoDAO.existeProduto(codigoT.getText().trim())){
                preencheCampos(codigoT.getText().trim());
            }else{
                limpar();
                JOptionPane.showMessageDialog(rootPane, "Produto não cadastrado!","ERRO",JOptionPane.ERROR_MESSAGE);
            }
            Conexao.desconectar(conexao);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void codigoTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTKeyReleased
        if((!codigoProd.equals(""))){
            if(!codigoT.getText().trim().equals(codigoProd))
                codigoT.setForeground(Color.red);
            else
                codigoT.setForeground(Color.black);
        }
    }//GEN-LAST:event_codigoTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEdiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEdiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEdiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEdiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DEdiProduto dialog = new DEdiProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField codigoT;
    private javax.swing.JButton confirmar;
    private javax.swing.JFormattedTextField custoT;
    private javax.swing.JTextArea descricaoT;
    private com.toedter.calendar.JDateChooser entregaT;
    private javax.swing.JButton fechar;
    private javax.swing.JComboBox<String> fornecedorT;
    private javax.swing.JComboBox<String> grupoT;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField marcaT;
    private javax.swing.JTextField nomeT;
    private javax.swing.JFormattedTextField precoT;
    private javax.swing.JSpinner quantidadeT;
    private javax.swing.JCheckBox valNula;
    private com.toedter.calendar.JDateChooser validadeT;
    // End of variables declaration//GEN-END:variables
}
